#!/usr/bin/env python3

import json
from pathlib import Path
from mptools.raw_to_notes import file_to_notes
from mptools.notes_into_final import add_notes_to_template

f = str((Path(__file__).parent / "data/raw/built-in-funcs.json").resolve())

notes_json_text = file_to_notes(f)
add_notes_to_template(notes_json_text)
