#!/usr/bin/env python3

import json
from pathlib import Path
from mptools.raw_to_notes import file_to_notes

f = str((Path(__file__).parent / "data/raw/built-in-funcs.json").resolve())

print(json.dumps(file_to_notes(f), indent=2, sort_keys=True))
